### ISSUE TITLE
how to restart the miner when error occurs?

### ISSUE THREAD

**Issue by yishuiliunian** [katatunix/polly#1]
when error occurs , i do not want to reboot he computer. i just want to restart the miner program? how to restart the miner program in your config.

**Comment by katatunix** [comment]
You can create a `KillMiner.bat` file with content `taskkill /f /t /im EthDcrMiner64.exe` and put it into the `Action` option. Replace `EthDcrMiner64.exe` with your miner process name.

By this way, when error occurs, the miner process will be killed. This is considered as a crash/exit, and the tool will handle it normally (send email, re-execute the miner again).

**Comment by yishuiliunian** [comment]
tks, it can kill the miner, but how to restart the miner?

**Comment by katatunix** [comment]
The tool (Polly) will automatically restart the miner after the miner is killed.

**Comment by yishuiliunian** [comment]
GOT it
