### ISSUE TITLE
Set tolerance for bad values

### ISSUE THREAD

**Issue by HermanCattaneo** [katatunix/polly#2]
Hi!

First of all i would like to say thank you for your work!

Seconds i wonder if there is an options to set tolerance time for example "fan=0%" "Bad" profile. I use a slow start method, in a cool room, so until all dags and epohs are generating some of my cards have 0% of fan because there dont need it.

I already tried that way:
```
        {
            "Bad" : [
                "fan=0%"
            ],
		"Tolerance" : { "DurationMinutes" : 1 },
		"Action" : "killminer.bat"
        },

```
then polly doesnt start, it hangs at processing the config file.

And i tried with:
```
        {
            "Bad" : [
                "fan=0%"
            ],
		"ToleranceMinutes" : 1,
		"Action" : "killminer.bat"
        },

```
in these case it just got ignored i think because its still starts killminer.bat

Thank you for your work and help!

Best regards,
Cattaneo

**Comment by katatunix** [comment]
Hello,

I’m on vacation. 

For now, if you know that your rig doesn’t have the problem of fan=0%. You can remove it from the config. 

I will update the tool to support your case soon.

**Comment by katatunix** [comment]
Updated for the version 3.0.

All you need is to specify a profile like this:

```
        {
            "Bad" : [ "fan=0%" ],
            "Tolerance" : { "DurationMinutes" : 1, "Good" : [ "fan=___fan=0%" ] },
            "Action" : "killminer.bat"
        }
```
Please check the new part in the `readme.md` file:

>If a `Bad` or `Good` option contains `___` (three underscore symbols), for example: `abc___xyz`, it means "contain `abc` but not `xyz`". This is useful when you cannot specify the full list of bad/good strings. For example, with a `Bad` option of `fan=0%`, it's crazy to list all cases for the `Good` option like `[ "fan=1", "fan=2", "fan=3" ... ]`. Instead, you can just write `[fan=___fan=0%]`.

**Comment by HermanCattaneo** [comment]
Thank you for your help and time! I hope your vacation was nice. I will test it tonight,
