### ISSUE TITLE
how can set the config.json path for the program?

### ISSUE THREAD

**Issue by yishuiliunian** [katatunix/polly#3]
how can set the config.json path for the program?

i do not want to use the config.json at the program path, instead of a custom path. how to set?

**Comment by katatunix** [comment]
Updated in v3.3: https://github.com/katatunix/polly/releases/tag/v3.3

Thank for your suggestion.

**Comment by yishuiliunian** [comment]
so how to use?

**Comment by katatunix** [comment]
from the new part in `readme.md`:

> * You can specify a different path of the config file other than the default `config.json`. Just pass the path as the first argument to `polly.exe` as specified in `polly.bat`. The path can be either absolute or relative to the current execution folder. If no any path is provided, the default `config.json` will be used.
